import {test} from 'node:test';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {readFileSync} from 'node:fs';
const base=process.env.SOCIAL_TEST_URL||'http://127.0.0.1:8088/api/social/index.php';
const cookie={};
async function call(who,action,data,query={}){
 const headers={};if(who&&cookie[who])headers.Cookie=cookie[who];if(data){headers['Content-Type']='application/json';headers['X-Social-Request']='1';}
 const r=await fetch(base+'?'+new URLSearchParams({action,...query}),{method:data?'POST':'GET',headers,body:data?JSON.stringify(data):undefined});
 if(who&&r.headers.get('set-cookie'))cookie[who]=r.headers.get('set-cookie').split(';')[0];
 const body=await r.json();return {status:r.status,...body};
}
const ok=r=>{assert.equal(r.status,200,JSON.stringify(r));return r;};
const tag=Date.now().toString(36),users=['admin','alice','bob','carol','dana'];let ids={},recovery={};
const password='Integration-test-password-123';
function cli(...args){return execFileSync('docker-compose',['-f','backend/social/tests/compose.yml','exec','-T','backend','php','social/manage.php',...args],{cwd:new URL('../../',import.meta.url),encoding:'utf8'});}
test('Social integration: tenant isolation, privacy, roles, booking, messages and module gates',async t=>{
 await t.test('register separate personal tenants, no automatic admin',async()=>{for(const u of users){const r=ok(await call(u,'register',{handle:u+'_'+tag,display_name:u,password}));recovery[u]=r.recovery_code;assert.equal(r.recovery_code.length,48);const b=ok(await call(u,'bootstrap'));ids[u]=Number(b.me.id);assert.equal(b.me.role,'member');assert.equal(b.me.status,'pending');}assert.equal((await call('alice','save_post',{module:'social',body:'no'})).status,403);});
 cli('admin','admin_'+tag);
 await t.test('manual approvals and technical settings use separate roles',async()=>{for(const u of users.slice(1))ok(await call('admin','moderate',{kind:'profile',id:ids[u],value:'active',reason:'Verified test profile'}));const b=ok(await call('admin','bootstrap'));assert.equal((await call('alice','save_settings',{settings:{registration:'immediate'},revision:b.revision})).status,403);ok(await call('admin','save_settings',{settings:{guest:true},revision:b.revision}));assert.equal((await call('admin','save_settings',{settings:{guest:false},revision:b.revision})).status,409);});
 let privateId,publicId;
 await t.test('public posts cross tenants, private posts do not',async()=>{privateId=ok(await call('alice','save_post',{module:'social',body:'friends only',visibility:'friends'})).id;publicId=ok(await call('alice','save_post',{module:'social',body:'public #LosSantos',visibility:'public'})).id;assert.equal((await call('bob','post',undefined,{id:privateId})).status,404);assert.equal((await call(null,'post',undefined,{id:privateId})).status,404);ok(await call('bob','post',undefined,{id:publicId}));ok(await call(null,'post',undefined,{id:publicId}));assert.equal((await call('bob','delete_post',{id:publicId})).status,403);});
 await t.test('friendship acceptance cannot be forged',async()=>{ok(await call('alice','friend',{id:ids.bob,action:'request'}));assert.equal((await call('alice','friend',{id:ids.bob,action:'accept'})).status,404);ok(await call('bob','friend',{id:ids.alice,action:'accept'}));ok(await call('bob','post',undefined,{id:privateId}));ok(await call('bob','friend',{id:ids.carol,action:'request'}));ok(await call('carol','friend',{id:ids.bob,action:'accept'}));const id=ok(await call('alice','save_post',{module:'social',body:'second degree',visibility:'friends_of_friends'})).id;ok(await call('carol','post',undefined,{id}));assert.equal((await call('dana','post',undefined,{id})).status,404);});
 await t.test('suspended session cannot use guest access to read friends content',async()=>{ok(await call('admin','moderate',{kind:'profile',id:ids.bob,value:'suspended',reason:'Test suspension'}));assert.equal((await call('bob','post',undefined,{id:privateId})).status,403);assert.equal((await call('bob','posts',undefined,{module:'social'})).status,403);ok(await call('bob','appeal',{reason:'Please review'}));ok(await call('admin','moderate',{kind:'profile',id:ids.bob,value:'active',reason:'Test restored'}));ok(await call('bob','post',undefined,{id:privateId}));});
 await t.test('likes switch rather than double count',async()=>{ok(await call('bob','reaction',{id:publicId,value:1}));const p=ok(await call('bob','reaction',{id:publicId,value:-1})).post;assert.equal(p.likes,0);assert.equal(p.dislikes,1);ok(await call('bob','comment',{id:publicId,body:'nice'}));assert.equal(ok(await call('alice','comments',undefined,{id:publicId})).items.length,1);});
 await t.test('private messages and multi-send have separate recipients',async()=>{for(const u of ['alice','bob','carol'])ok(await call(u,'save_profile',{display_name:u,privacy:'public',messages:'public',requests:'public',wall:'friends',default_visibility:'friends',signature:'Regards'}));ok(await call('alice','send',{recipients:[ids.bob,ids.carol],body:'hello **friends**',signature:true}));const b=ok(await call('bob','messages',undefined,{with:ids.alice}));assert.equal(b.items.length,1);assert.equal(Number(b.items[0].recipient),ids.bob);assert.ok(!JSON.stringify(b).includes('recipients'));assert.equal(ok(await call('dana','messages',undefined,{with:ids.alice})).items.length,0);assert.equal(ok(await call('admin','messages',undefined,{with:ids.alice})).items.length,0);});
 await t.test('block overrides friendship and public visibility',async()=>{ok(await call('bob','block',{id:ids.alice}));assert.equal((await call('bob','post',undefined,{id:publicId})).status,404);assert.equal((await call('alice','send',{recipients:[ids.bob],body:'blocked'})).status,403);ok(await call('bob','block',{id:ids.alice,remove:true}));});
 await t.test('shared post does not expand source visibility',async()=>{ok(await call('alice','friend',{id:ids.bob,action:'request'}));ok(await call('bob','friend',{id:ids.alice,action:'accept'}));const id=ok(await call('bob','save_post',{module:'social',shared_id:privateId,body:'',visibility:'public'})).id;assert.equal(ok(await call('dana','post',undefined,{id})).post.shared,null);assert.ok(ok(await call('alice','post',undefined,{id})).post.shared);});
 await t.test('discovery shows authorized opening status and rejects unrelated users',async()=>{const company=ok(await call('admin','save_company',{name:'Discovery Garage',members:[ids.alice]})).id;assert.equal((await call('dana','company_open',{id:company,minutes:120})).status,403);ok(await call('alice','company_open',{id:company,minutes:120}));assert.ok(ok(await call(null,'discovery')).open_companies.some(c=>Number(c.id)===company));ok(await call('alice','company_open',{id:company,minutes:0}));assert.ok(!ok(await call(null,'discovery')).open_companies.some(c=>Number(c.id)===company));assert.ok(ok(await call('dana','discovery')).highlights.every(p=>p.visibility==='public'));});
 await t.test('bookmarks are private and do not grant access to deleted content',async()=>{const id=ok(await call('alice','save_post',{module:'social',body:'Bookmark test',visibility:'public'})).id;ok(await call('bob','bookmark',{id}));ok(await call('bob','bookmark',{id}));assert.equal(ok(await call('bob','bookmarks')).items.filter(p=>Number(p.id)===id).length,1);assert.equal(ok(await call('dana','bookmarks',undefined,{profile_id:ids.bob})).items.length,0);ok(await call('alice','delete_post',{id}));assert.ok(!ok(await call('bob','bookmarks')).items.some(p=>Number(p.id)===id));ok(await call('bob','bookmark',{id,remove:true}));assert.equal((await call(null,'bookmarks')).status,401);});
 await t.test('staff update directory details but cannot self-verify',async()=>{const id=ok(await call('admin','save_company',{name:'Verified Garage',members:[ids.alice],verified:true,location:'Strawberry'})).id;assert.equal((await call('alice','save_company',{id,name:'Verified Garage',members:[ids.alice],verified:true})).status,403);assert.equal((await call('dana','company_details',{id,description:'forged'})).status,403);ok(await call('alice','company_details',{id,description:'Our workshop',location:'Strawberry',contact:'Message us',verified:false}));const c=ok(await call(null,'companies')).items.find(c=>Number(c.id)===id);assert.equal(Number(c.verified),1);assert.equal(c.location,'Strawberry');});
 await t.test('company services, hours and map coordinates persist with bounds checks',async()=>{const id=ok(await call('admin','save_company',{name:'Map Garage',members:[ids.alice]})).id;ok(await call('alice','company_details',{id,services:'Repairs',service_area:'Los Santos',opening_hours:'Mo–Fr 18:00–23:00',map_x:44.4,map_y:80}));let c=ok(await call(null,'companies')).items.find(c=>Number(c.id)===id);assert.equal(c.services,'Repairs');assert.equal(Number(c.map_x),44.4);assert.equal((await call('alice','company_details',{id,map_x:101,map_y:80})).status,422);c=ok(await call(null,'companies')).items.find(c=>Number(c.id)===id);assert.equal(Number(c.map_x),44.4);assert.equal((await call('dana','company_details',{id,map_x:20,map_y:20})).status,403);});
 let ad;
 await t.test('advertising requests reserve only once and wait for payment',async()=>{const company=ok(await call('admin','save_company',{name:'Test Motors',members:[ids.alice]})).id;const starts=new Date(Date.now()+86400000).toISOString(),ends=new Date(Date.now()+172800000).toISOString();const slot=ok(await call('admin','save_slot',{name:'Header',placement:'header',starts_at:starts,ends_at:ends,price:500,active:true})).id;ad=ok(await call('alice','request_ad',{company_id:company,slot_id:slot,title:'Hello',body:'Test',starts_at:starts,ends_at:ends})).id;const other=ok(await call('alice','request_ad',{company_id:company,slot_id:slot,title:'Second',body:'Test',starts_at:starts,ends_at:ends})).id;ok(await call('admin','decide_ad',{id:ad,decision:'accepted'}));assert.equal((await call('admin','decide_ad',{id:other,decision:'accepted'})).status,409);assert.equal(Number(ok(await call('alice','ads')).items.find(a=>Number(a.id)===ad).paid),0);ok(await call('admin','decide_ad',{id:ad,decision:'paid'}));assert.equal(ok(await call('alice','notifications')).items.filter(n=>n.body.includes('500')).length,1);});
 await t.test('disabled module denies API and shared access',async()=>{let b=ok(await call('admin','bootstrap'));ok(await call('admin','save_settings',{settings:{modules:{social:false,messages:false}},revision:b.revision}));assert.equal((await call('alice','post',undefined,{id:publicId})).status,404);assert.equal((await call('alice','messages')).status,404);assert.equal((await call('alice','purge',{module:'social'})).status,403);const preview=ok(await call('admin','purge',{module:'messages'}));assert.ok(preview.messages>0);assert.equal((await call('admin','purge',{module:'messages',confirm:'yes'})).status,422);b=ok(await call('admin','bootstrap'));ok(await call('admin','save_settings',{settings:{modules:{social:true,messages:true}},revision:b.revision}));});

 await t.test('media URLs enforce ownership, privacy and video approval',async()=>{
   async function uploadFile(who,buffer,name,module,purpose='post'){
     const form=new FormData();form.set('file',new Blob([buffer]),name);form.set('module',module);form.set('purpose',purpose);
     const response=await fetch(base+'?action=upload',{method:'POST',headers:{Cookie:cookie[who],'X-Social-Request':'1'},body:form});return {status:response.status,...await response.json()};
   }
   async function mediaStatus(who,id){const r=await fetch(base+'?action=media&id='+id,{headers:who?{Cookie:cookie[who]}:{}});await r.arrayBuffer();return r.status;}
   const image=readFileSync(new URL('./fixtures/image.jpg',import.meta.url));
   const file=ok(await uploadFile('alice',image,'photo.jpg','gram'));
   assert.equal(await mediaStatus('bob',file.id),404);
   const post=ok(await call('alice','save_post',{module:'gram',body:'private photo',visibility:'friends',media:[file.id]}));
   assert.equal(await mediaStatus('bob',file.id),200);assert.equal(await mediaStatus(null,file.id),404);
   assert.equal((await call('bob','save_post',{module:'gram',body:'stolen image',visibility:'public',media:[file.id]})).status,422);
   assert.equal((await uploadFile('alice',Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>'),'x.svg','gram')).status,422);
   const avatar=ok(await uploadFile('alice',image,'avatar.jpg','social','profile'));
   ok(await call('alice','save_profile',{display_name:'alice',privacy:'friends',avatar_id:avatar.id}));
   assert.equal(await mediaStatus('bob',avatar.id),200);assert.equal(await mediaStatus('dana',avatar.id),404);
   let b=ok(await call('admin','bootstrap'));ok(await call('admin','save_settings',{settings:{modules:{gram:false,social:false}},revision:b.revision}));
   assert.equal(await mediaStatus('alice',file.id),404);assert.equal(await mediaStatus('bob',avatar.id),200);
   b=ok(await call('admin','bootstrap'));ok(await call('admin','save_settings',{settings:{modules:{gram:true,social:true}},revision:b.revision}));
   execFileSync('docker-compose',['-f','backend/social/tests/compose.yml','exec','-T','backend','ffmpeg','-v','error','-y','-f','lavfi','-i','color=c=blue:s=320x180:d=1','-c:v','libx264','-pix_fmt','yuv420p','/tmp/social-fixture.mp4'],{cwd:new URL('../../',import.meta.url)});
   const video=execFileSync('docker-compose',['-f','backend/social/tests/compose.yml','exec','-T','backend','cat','/tmp/social-fixture.mp4'],{cwd:new URL('../../',import.meta.url)});
   const vf=ok(await uploadFile('alice',video,'clip.mp4','video'));
   const vp=ok(await call('alice','save_post',{module:'video',title:'Test video',body:'one second',visibility:'public',media:[vf.id]}));
   assert.equal((await call('admin','moderate',{kind:'video',id:vp.id,value:'published',reason:'Too early'})).status,409);
   assert.notEqual(ok(await call(null,'discovery')).video?.id,vp.id);
   execFileSync('docker-compose',['-f','backend/social/tests/compose.yml','exec','-T','backend','php','social/worker.php','--once'],{cwd:new URL('../../',import.meta.url)});
   assert.equal(await mediaStatus('bob',vf.id),404);assert.equal(await mediaStatus('admin',vf.id),200);
   ok(await call('admin','moderate',{kind:'video',id:vp.id,value:'published',reason:'Reviewed'}));
   assert.equal(Number(ok(await call(null,'discovery')).video.id),Number(vp.id));
   assert.equal(await mediaStatus('bob',vf.id),200);
   const range=await fetch(base+'?action=media&id='+vf.id,{headers:{Cookie:cookie.bob,Range:'bytes=0-99'}});assert.equal(range.status,206);assert.equal((await range.arrayBuffer()).byteLength,100);
   ok(await call('alice','save_post',{id:vp.id,module:'video',title:'Edited video',body:'edit',visibility:'public',media:[vf.id]}));assert.equal(await mediaStatus('bob',vf.id),404);
   ok(await call('alice','delete_post',{id:post.id}));assert.equal(await mediaStatus('bob',file.id),404);
 });
 await t.test('recovery invalidates prior sessions and rotates code',async()=>{const oldCookie=cookie.carol;const r=ok(await call('carol','recover',{handle:'carol_'+tag,password:'A-new-long-password-123',recovery_code:recovery.carol}));assert.notEqual(r.recovery_code,recovery.carol);cookie.carol=oldCookie;assert.equal((await call('carol','messages')).status,401);});
 await t.test('cross-site and wrong-method writes are rejected',async()=>{const r=await fetch(base+'?action=save_post',{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie.alice},body:'{}'});assert.equal(r.status,403);assert.equal((await call('alice','save_post')).status,405);});
 console.log('Test users:',users.map(u=>u+'_'+tag).join(', '));
});
