ALTER TABLE kdd_social_companies ADD COLUMN IF NOT EXISTS services VARCHAR(1000) NOT NULL DEFAULT '';
ALTER TABLE kdd_social_companies ADD COLUMN IF NOT EXISTS service_area VARCHAR(500) NOT NULL DEFAULT '';
ALTER TABLE kdd_social_companies ADD COLUMN IF NOT EXISTS opening_hours VARCHAR(1500) NOT NULL DEFAULT '';
ALTER TABLE kdd_social_companies ADD COLUMN IF NOT EXISTS photo_id INT NULL;
ALTER TABLE kdd_social_companies ADD COLUMN IF NOT EXISTS map_x DECIMAL(7,4) NULL;
ALTER TABLE kdd_social_companies ADD COLUMN IF NOT EXISTS map_y DECIMAL(7,4) NULL;
