<script setup lang="ts">
import LawsReader from './LawsReader.vue';
import LawsVersion from './LawsVersion.vue';
import { computed, onMounted, onUnmounted, ref } from 'vue';
type Row = Record<string, any>;
const props = withDefaults(defineProps<{ endpoint?: string; cadUrl?: string; editorial?: boolean; windowId?: string }>(), { endpoint: '/api/social/laws.php', cadUrl: '', editorial:false });
const state = ref<Row>({}), books = ref<Row[]>([]), selected = ref<Row | null>(null), articles = ref<Row[]>([]), rights = ref<Row>({}), admin = ref<Row>({authorities:[],grants:[],audit:[]});
const globalQuery = ref(''), searchResults = ref<Row[] | null>(null);
const templates = [
 {title:'Strafgesetzbuch', description:'Straftaten und Rechtsfolgen. Vorgesehene Kapitel: Allgemeiner Teil, Personen, Eigentum, öffentliche Ordnung.'},
 {title:'Straßenverkehrsordnung', description:'Regeln für den Straßenverkehr. Vorgesehene Kapitel: Verkehrsregeln, Fahrerlaubnis, Fahrzeuge, Kontrollen.'},
 {title:'Gewerbeordnung', description:'Regeln für Unternehmen. Vorgesehene Kapitel: Anmeldung, Genehmigungen, Betriebspflichten, Aufsicht.'},
 {title:'Strafprozessordnung', description:'Ablauf von Ermittlungen und Gerichtsverfahren. Vorgesehene Kapitel: Zuständigkeit, Ermittlungen, Beschuldigtenrechte, Verfahren.'},
 {title:'Verfassung', description:'Grundlagen der Community. Vorgesehene Kapitel: Grundrechte, Staatsorgane, Zuständigkeiten, Gesetzgebung.'}
];
const query = ref(''), error = ref(''), notice = ref(''), busy = ref(false), history = ref<Row[] | null>(null), editing = ref<Row | null>(null), newBook = ref(''), bookDescription = ref(''), publishDate = ref('');
const canEditApp = computed(()=>state.value.admin||Object.values(state.value.rights||{}).some(Boolean));
const editingSnapshot=ref('');
const dirty=computed(()=>!!editing.value&&JSON.stringify(editing.value)!==editingSnapshot.value);
function allowLeave(){return !dirty.value||window.confirm('Ungespeicherte Änderungen verwerfen?');}
function confirmDiscard(){return window.confirm('Diesen unveröffentlichten Entwurf endgültig verwerfen?');}
function cancelEditing(){if(allowLeave())editing.value=null;}
const beforeUnload=(event:BeforeUnloadEvent)=>{if(dirty.value){event.preventDefault();event.returnValue='';}};
const beforeClose=(event:Event)=>{const id=(event as CustomEvent).detail?.windowId;if((!id||id===props.windowId)&&!allowLeave())event.preventDefault();};
const editorPreview = ref(false), editorSection = ref('content');
const grant = ref<Row>({authority_id:0,draft_read:false,edit:false,publish:false,repeal:false});
const shown = computed(() => articles.value.filter(a => [a.number,...[a.current,a.draft,a.scheduled].flatMap(v=>v?[v.title,v.chapter,v.body,...(v.subsections||[]).flatMap((p:Row)=>[p.number,p.title,p.body])]:[])].join(' ').toLocaleLowerCase().includes(query.value.toLocaleLowerCase())));
const chapters = computed(() => {
 const groups: {title:string; articles:Row[]}[]=[];
 for(const a of shown.value){const title=(a.current||a.scheduled||a.draft)?.chapter||'Allgemeine Bestimmungen';let group=groups.find(g=>g.title===title);if(!group){group={title,articles:[]};groups.push(group);}group.articles.push(a);}return groups;
});
function jump(id:number|string){document.getElementById('law-'+id)?.scrollIntoView({behavior:'smooth',block:'start'});}
function movePart(index:number,delta:number){const parts=editing.value!.subsections;[parts[index],parts[index+delta]]=[parts[index+delta],parts[index]];}
async function api(action:string, data?:Row, q:Row={}) {
 const response = await fetch(props.endpoint+'?'+new URLSearchParams({action,...q}),{credentials:'include',method:data?'POST':'GET',headers:{...(props.endpoint.includes('/social/')?{'X-Social-Account':sessionStorage.getItem('social-account')||'0'}:{}),...(data?{'Content-Type':'application/json','X-Laws-Request':'1'}:{})},body:data?JSON.stringify(data):undefined});
 const result = await response.json();if(!response.ok)throw new Error(result.error||'Anfrage fehlgeschlagen.');return result;
}
async function run(fn:()=>Promise<void>) { if(busy.value)return;busy.value=true;error.value='';notice.value='';try{await fn();}catch(e){error.value=e instanceof Error?e.message:'Anfrage fehlgeschlagen.';}finally{busy.value=false;} }
async function refresh() { state.value=await api('bootstrap');if(state.value.enabled&&state.value.can_read||state.value.admin)books.value=(await api('books')).items;if(state.value.admin)admin.value=await api('administration'); }
async function searchAll(){searchResults.value=(await api('search',undefined,{q:globalQuery.value.trim()})).items;}
async function showResult(result:Row){await open(result.book_id);searchResults.value=null;requestAnimationFrame(()=>document.getElementById('law-'+result.article.id)?.scrollIntoView());}
async function open(id:number) {const r=await api('book',undefined,{id});selected.value=r.book;articles.value=r.articles;rights.value=r.rights;editing.value=null;history.value=null;query.value='';}
function edit(a?:Row) {editorPreview.value=false;const v=a?.draft||a?.current||a?.scheduled;editing.value={article_id:a?.id||0,book_id:selected.value!.id,revision:a?.revision||0,number:a?.number||'',title:v?.title||'',chapter:v?.chapter||'',body:v?.body||'',subsections:JSON.parse(JSON.stringify(v?.subsections||[])),amount_kind:v?.amount_kind||'fine',amount_min:v?.amount_min??'',amount_max:v?.amount_max??'',reason:a?.draft?.reason||''};editingSnapshot.value=JSON.stringify(editing.value);}
async function saveDraft(){await api('save_draft',editing.value!);editingSnapshot.value=JSON.stringify(editing.value);await open(Number(selected.value!.id));notice.value='Entwurf gespeichert. Die veröffentlichte Fassung bleibt unverändert.';}
async function publish(a:Row){let effective_at='';if(publishDate.value)effective_at=new Date(publishDate.value).toISOString().replace(/\.\d{3}Z$/,'Z');await api('publish',{article_id:a.id,revision:a.revision,effective_at});await open(Number(selected.value!.id));notice.value='Fassung veröffentlicht.';}
async function repeal(a:Row) {editing.value={repeal:true,article_id:a.id,revision:a.revision,number:a.number,reason:''};editingSnapshot.value=JSON.stringify(editing.value);}
async function saveBook(){const r=await api('save_book',{title:newBook.value,description:bookDescription.value});newBook.value='';bookDescription.value='';await refresh();await open(r.id);}
async function saveGrant(){await api('grant',{...grant.value});await refresh();notice.value='Zuständigkeit gespeichert. Mitarbeiter benötigen zusätzlich passende CAD-Rollenrechte.';}
function loadGrant(){const existing=admin.value.grants.find((g:Row)=>Number(g.authority_id)===Number(grant.value.authority_id));for(const key of ['draft_read','edit','publish','repeal'])grant.value[key]=!!Number(existing?.[key]||0);}
function articleLink(id:number){return location.href.split('#')[0]+(location.hash.startsWith('#/laws')?'#/laws/':'#law-')+id;}
async function followLink(){const linked=Number(location.hash.match(/(?:#\/laws\/|#law-)(\d+)/)?.[1]||0);if(linked&&state.value.can_read){for(const b of books.value){await open(Number(b.id));if(articles.value.some(a=>a.id===linked)){requestAnimationFrame(()=>document.getElementById('law-'+linked)?.scrollIntoView());break;}}}}
const onHash=()=>run(followLink);
onMounted(()=>{if(!props.editorial)return;window.addEventListener('beforeunload',beforeUnload);window.addEventListener('cad-before-close',beforeClose);window.addEventListener('hashchange',onHash);run(async()=>{await refresh();if(books.value.length)await open(Number(books.value[0].id));await followLink();});});
onUnmounted(()=>{window.removeEventListener('hashchange',onHash);window.removeEventListener('beforeunload',beforeUnload);window.removeEventListener('cad-before-close',beforeClose);});
</script>
<template>
<LawsReader v-if="!editorial" :endpoint="endpoint"/>
<section v-else class="laws-app" :aria-busy="busy">
 <header class="law-heading"><div><span class="law-eyebrow">RECHT & ORDNUNG</span><h1>Gesetze-Redaktion</h1><p>Gesetzbücher pflegen, Änderungen vorbereiten und Fassungen veröffentlichen.</p></div><span class="law-context">{{ state.context ? 'CAD · '+state.context.name : 'Leseansicht' }}</span></header>
 <nav v-if="state.admin&&!editing" class="editor-sections" aria-label="Redaktionsbereiche"><button :aria-pressed="editorSection==='content'" @click="editorSection='content'">Inhalte</button><button :aria-pressed="editorSection==='administration'" @click="editorSection='administration'">Zugriffe und Einstellungen</button></nav>
 <p v-if="error" class="law-error" role="alert">{{error}}</p><p v-if="notice" class="law-notice" role="status">{{notice}}</p>
 <p v-if="state.enabled===false">Die Gesetze-App ist deaktiviert.</p>
 <p v-else-if="state.can_read===false">Zum Lesen bitte anmelden. Der Gastzugang für Gesetze ist derzeit ausgeschaltet.</p>
 <a v-if="cadUrl&&!state.context" :href="cadUrl.replace(/\/$/,'')+'/laws-editor'" target="_blank" rel="noopener">Im CAD öffnen und bearbeiten ↗</a>
 <p v-if="state.can_read&&!state.admin&&!Object.values(state.rights||{}).some(Boolean)" class="law-notice">Für die Redaktion benötigst du eine Freigabe für die Gesetze-App und passende CAD-Rollenrechte.</p>
 <details v-if="state.admin&&!editing&&editorSection==='administration'" class="law-panel" open><summary>Community-Verwaltung</summary>
  <form @submit.prevent="run(async()=>{await api('settings',{enabled:state.enabled,guest:state.guest,revision:state.revision});await refresh();notice='Einstellungen gespeichert.';})"><label class="law-check"><input type="checkbox" v-model="state.enabled"/>Gesetze-App aktiviert</label><label class="law-check"><input type="checkbox" v-model="state.guest"/>Veröffentlichte Gesetze ohne Anmeldung lesbar</label><button :disabled="busy">Einstellungen speichern</button></form>

  <details class="law-panel"><summary>Zugriff auf die gesamte Gesetze-App</summary><p>Das System-CAD verwaltet die Zugriffe und behält selbst alle Rechte.</p>    <form @submit.prevent="run(saveGrant)"><label>Fraktion<select v-model="grant.authority_id" @change="loadGrant" required><option :value="0" disabled>Fraktion auswählen</option><option v-for="a in admin.authorities" :key="a.id" :value="Number(a.id)">{{a.display_name}}</option></select></label><label v-for="[key,label] in [['draft_read','Entwürfe lesen'],['edit','Bearbeiten'],['publish','Veröffentlichen'],['repeal','Außer Kraft setzen']]" :key="key" class="law-check"><input type="checkbox" v-model="grant[key]"/>{{label}}</label><p>Die Freigabe gilt für alle Gesetzbücher und Paragraphen. Mitarbeiter benötigen zusätzlich passende Rollenrechte. Alle Haken entfernen entzieht der Behörde den Zugang zur Redaktion.</p><button :disabled="busy||!grant.authority_id">Zuständigkeit speichern</button></form></details>
  <details><summary>Änderungsprotokoll</summary><ol><li v-for="entry in admin.audit" :key="entry.id">{{entry.created_at}} UTC · {{entry.action}} · CAD-Benutzer {{entry.actor_id}} / Fraktion {{entry.authority_id}}<pre>{{entry.details}}</pre></li></ol></details>
 </details>
 <details v-if="editorSection==='content'&&state.rights?.edit&&!editing" class="law-panel law-create-book"><summary>Neues Gesetzbuch</summary>  <form @submit.prevent="run(saveBook)"><h3>Gesetzbuch anlegen</h3><p>Vorlage auswählen und an eure Community anpassen. Es werden keine Gesetze automatisch veröffentlicht.</p><div class="law-tools"><button v-for="t in templates" :key="t.title" type="button" @click="newBook=t.title;bookDescription=t.description">{{t.title}}</button></div><label>Titel<input v-model="newBook" required maxlength="160" placeholder="Zum Beispiel Strafgesetzbuch"/></label><label>Beschreibung<textarea v-model="bookDescription" maxlength="4000"/></label><button :disabled="busy">Gesetzbuch anlegen</button></form></details>
 <section v-if="editorSection==='content'&&!editing && canEditApp && state.can_read&&(state.enabled||state.admin)" class="law-panel law-search">
  <form class="law-tools" @submit.prevent="run(searchAll)"><label>Alle Gesetzbücher durchsuchen<input v-model="globalQuery" type="search" maxlength="200" placeholder="Paragraph, Titel, Kapitel oder Gesetzestext"/></label><button :disabled="busy||!globalQuery.trim()">Suchen</button><button v-if="searchResults!==null" type="button" @click="searchResults=null;globalQuery=''">Zurücksetzen</button></form>
  <div v-if="searchResults!==null" aria-live="polite"><h2>{{searchResults.length}} Treffer</h2><p v-if="!searchResults.length">Keine passenden Paragraphen gefunden.</p><button v-for="r in searchResults" :key="r.article.id" class="law-result" :disabled="busy" @click="run(()=>showResult(r))"><small>{{r.book_title}}</small><br/>§ {{r.article.number}} · {{(r.article.current||r.article.scheduled||r.article.draft)?.title}}</button></div>
 </section>
 <div v-if="editorSection==='content'&&canEditApp&&state.can_read&&(state.enabled||state.admin)" class="law-layout" :class="{'editor-active':editing}">
  <nav class="law-panel law-toc" aria-label="Inhaltsverzeichnis"><label class="law-book-select">Gesetzbuch<select :value="selected?.id || ''" :disabled="busy" @change="run(()=>open(Number(($event.target as HTMLSelectElement).value)))"><option value="" disabled>Gesetzbuch auswählen</option><option v-for="b in books" :key="b.id" :value="b.id">{{b.title}}</option></select></label><h2>Inhaltsverzeichnis</h2><p v-if="!books.length">Noch keine Gesetzbücher angelegt.</p><p v-else-if="!shown.length">Noch keine sichtbaren Paragraphen.</p><section v-for="chapter in chapters" :key="chapter.title" class="toc-chapter"><h3>{{chapter.title}}</h3><div v-for="a in chapter.articles" :key="a.id"><button @click="jump(a.id)"><span>§ {{a.number}}</span> {{(a.current||a.scheduled||a.draft)?.title}}</button><button v-for="part in a.current?.subsections||[]" :key="part.number" class="toc-subsection" @click="jump(a.id+'-'+part.number)">({{part.number}}) {{part.title||part.body.slice(0,45)}}</button></div></section></nav>
  <main v-if="selected" class="law-content"><div v-if="!editing" class="law-tools"><span class="law-badge">{{Number(selected.published)?'Öffentliches Gesetzbuch':'Unveröffentlichtes Gesetzbuch'}}</span><button v-if="rights.publish" :disabled="busy" @click="run(async()=>{await api('book_visibility',{id:selected!.id,revision:selected!.revision,published:!Number(selected!.published)});await refresh();await open(Number(selected!.id));})">{{Number(selected.published)?'Gesetzbuch zurückziehen':'Gesetzbuch veröffentlichen'}}</button></div><h2>{{selected.title}}</h2><p>{{selected.description}}</p>
   <details v-if="rights.edit&&!editing" class="law-panel"><summary>Gesetzbuch bearbeiten</summary>
    <form @submit.prevent="run(async()=>{await api('save_book',selected!);await refresh();await open(Number(selected!.id));})"><label>Titel<input v-model="selected.title" maxlength="160" required/></label><label>Beschreibung<textarea v-model="selected.description" maxlength="4000"/></label><button :disabled="busy">Gesetzbuch speichern</button></form>

   </details>
   <div class="law-tools" v-if="!editing"><label>Paragraphen durchsuchen<input v-model="query" type="search" placeholder="Nummer, Titel oder Inhalt"/></label><button v-if="rights.edit" :disabled="busy" @click="edit()">Paragraph anlegen</button></div>
   <form v-if="editing" class="law-panel law-editor" @submit.prevent="run(async()=>{if(editing!.repeal){await api('repeal',editing!);await open(Number(selected!.id));notice='Fassung außer Kraft gesetzt.';}else await saveDraft();})">
    <div class="law-tools"><h3>{{editing.repeal?'Außer Kraft setzen: § '+editing.number:'Paragraph bearbeiten'}}</h3><button v-if="!editing.repeal" type="button" @click="editorPreview=!editorPreview">{{editorPreview?'Weiter bearbeiten':'Vorschau'}}</button></div><p v-if="!editing.repeal" class="law-meta">{{selected.title}} · Änderungen werden als Entwurf gespeichert und separat veröffentlicht.</p><section v-if="editorPreview" class="law-panel law-article"><h3>§ {{editing.number}} · {{editing.title}}</h3><LawsVersion :version="editing"/></section><div v-show="!editorPreview">
    <template v-if="!editing.repeal"><label>Paragraphennummer<input v-model="editing.number" :disabled="!!editing.article_id" required maxlength="40"/></label><label>Kapitel<input v-model="editing.chapter" maxlength="160"/></label><label>Titel<input v-model="editing.title" required maxlength="200"/></label><label>Gesetzestext<textarea v-model="editing.body" rows="5" required maxlength="100000" placeholder="Grundregel oder Einleitung des Paragraphen"/></label>
    <fieldset class="law-subsection-editor"><legend>Unterparagraphen / Absätze</legend><p>Zum Beispiel (1), (2) oder (2a). Die Reihenfolge lässt sich verschieben.</p><section v-for="(part,index) in editing.subsections" :key="index" class="law-part-editor"><div class="law-tools"><label>Absatznummer<input v-model="part.number" required maxlength="20"/></label><label>Zwischenüberschrift<input v-model="part.title" maxlength="200"/></label></div><label>Absatztext<textarea v-model="part.body" rows="3" required maxlength="10000"/></label><div class="law-tools"><button type="button" :disabled="Number(index)===0" @click="movePart(Number(index),-1)">Nach oben</button><button type="button" :disabled="Number(index)===editing.subsections.length-1" @click="movePart(Number(index),1)">Nach unten</button><button type="button" @click="editing.subsections.splice(index,1)">Absatz entfernen</button></div></section><button type="button" :disabled="editing.subsections.length>=100" @click="editing.subsections.push({number:'',title:'',body:''})">Absatz hinzufügen</button></fieldset>
    <fieldset class="law-subsection-editor"><legend>Geldstrafe oder Gebühr</legend><p>Leer lassen, wenn kein Betrag vorgesehen ist. Ohne Höchstbetrag gilt ein fester Betrag.</p><label>Betragsart<select v-model="editing.amount_kind"><option value="fine">Geldstrafe</option><option value="fee">Gebühr</option></select></label><div class="law-tools"><label>Betrag / Mindestbetrag ($)<input v-model="editing.amount_min" type="number" min="0" max="9999999999.99" step="0.01"/></label><label>Höchstbetrag (optional, $)<input v-model="editing.amount_max" type="number" min="0" max="9999999999.99" step="0.01"/></label></div></fieldset></template>
    <label>Begründung<textarea v-model="editing.reason" required maxlength="4000"/></label></div><div class="law-tools"><button :disabled="busy">{{editing.repeal?'Aufhebung bestätigen':'Entwurf speichern'}}</button><button type="button" :disabled="busy" @click="cancelEditing">Abbrechen</button></div>
   </form>
   <template v-if="!editing"><label v-if="rights.publish" class="law-panel">Neue Veröffentlichungen gültig ab (leer = sofort)<input type="datetime-local" v-model="publishDate"/><small>Die ausgewählte Zeit entspricht deiner lokalen Zeitzone.</small></label>
   <p v-if="!shown.length">Keine sichtbaren Paragraphen gefunden.</p>
   <article v-for="a in shown" :key="a.id" :id="'law-'+a.id" class="law-panel law-article">
    <h3>§ {{a.number}} · {{(a.current||a.scheduled||a.draft)?.title}}</h3>
    <template v-if="a.current"><span class="law-badge">{{a.current.repealed_at?'Außer Kraft':'Geltende Fassung'}}</span><p class="law-meta"><template v-if="a.current.chapter">{{a.current.chapter}} · </template>Gültig seit {{a.current.effective_at}} UTC · Herausgeber: {{a.current.publisher}}</p><LawsVersion :version="a.current" :anchor-prefix="'law-'+a.id"/><p v-if="a.current.repealed_at">Außer Kraft seit {{a.current.repealed_at}} UTC: {{a.current.repeal_reason}}</p></template>
    <p v-else>Dieser Paragraph hat noch keine geltende Fassung.</p>
    <details v-if="a.scheduled"><summary>Zukünftige Fassung · gültig ab {{a.scheduled.effective_at}} UTC</summary><h4>{{a.scheduled.title}}</h4><LawsVersion :version="a.scheduled"/></details>
    <details v-if="a.draft" class="law-draft" open><summary>Entwurf · nicht veröffentlicht</summary><h4>{{a.draft.title}}</h4><LawsVersion :version="a.draft"/><p>Begründung: {{a.draft.reason}}</p><button v-if="rights.publish" :disabled="busy" @click="run(()=>publish(a))">Diese Fassung veröffentlichen</button><button v-if="rights.edit" :disabled="busy" @click="run(async()=>{if(!confirmDiscard())return;await api('discard',{article_id:a.id,revision:a.revision});await open(Number(selected!.id));})">Entwurf verwerfen</button></details>
    <footer class="law-tools"><a :href="articleLink(a.id)">Direktlink</a><button :disabled="busy" @click="run(async()=>{history=(await api('history',undefined,{id:a.id})).items;})">Frühere Fassungen</button><button v-if="rights.edit" :disabled="busy" @click="edit(a)">{{a.draft?'Entwurf bearbeiten':'Änderung entwerfen'}}</button><button v-if="rights.repeal&&a.current&&!a.current.repealed_at" :disabled="busy" @click="repeal(a)">Außer Kraft setzen</button></footer>
   </article>
   <section v-if="history" class="law-panel"><h3>Veröffentlichte Fassungen</h3><button @click="history=null">Schließen</button><p v-if="!history.length">Noch keine veröffentlichten Fassungen.</p><article v-for="v in history" :key="v.id"><h4>{{v.title}} · {{v.effective_at}} UTC</h4><p>{{v.publisher}} · {{v.reason}}</p><LawsVersion :version="v"/><hr/></article></section>
   </template>
  </main><main v-else class="law-panel"><h2>Das Gesetzbuch deiner Community</h2><p>Hier findet ihr veröffentlichte Regeln, Gebühren und Geldstrafen. Sobald ein Gesetzbuch angelegt ist, erscheint links sein Inhaltsverzeichnis.</p></main>
 </div>
</section>
</template>
<style scoped>
.laws-app{--law-bg:var(--surface,#fff);--law-text:var(--text,#202c35);--law-line:var(--line,#d7dee2);color:var(--law-text);background:var(--law-bg);padding:clamp(16px,3vw,36px);border-radius:18px;max-width:1280px;margin:20px auto;font:inherit;min-height:60vh}.law-heading,.law-tools{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap}.law-heading{margin-bottom:24px}.law-eyebrow{font-size:11px;letter-spacing:.16em}.laws-app h1{font-size:32px;margin:8px 0}.laws-app h2{font-size:23px}.laws-app h3{font-size:18px;line-height:1.4;margin:0 0 12px}.laws-app p{margin:12px 0}.law-context,.law-badge{display:inline-block;padding:6px 10px;border:1px solid var(--law-line);border-radius:8px;font-size:12px}.law-layout{display:grid;grid-template-columns:230px minmax(0,1fr);gap:24px;margin-top:22px}.law-panel{border:1px solid var(--law-line);border-radius:12px;padding:18px;margin-bottom:16px}.law-result{display:block;width:100%;text-align:left;margin:8px 0}.law-layout nav{align-self:start}.law-layout nav button{display:block;width:100%;text-align:left;margin:8px 0}.laws-app button{font:inherit;color:inherit;border:1px solid var(--law-line);border-radius:8px;background:transparent;padding:9px 12px;cursor:pointer}.laws-app button:disabled{opacity:.5;cursor:wait}.laws-app button.active,.laws-app button:hover:not(:disabled){border-color:var(--brand,#087f80);background:color-mix(in srgb,var(--brand,#087f80) 10%,transparent)}.laws-app input:not([type=checkbox]),.laws-app textarea,.laws-app select{display:block;width:100%;font:inherit;color:inherit;background:var(--law-bg);border:1px solid var(--law-line);padding:9px;border-radius:6px;box-sizing:border-box}.laws-app label{display:block;margin:12px 0;flex:1}.laws-app .law-check{display:flex;align-items:center;gap:8px}.laws-app input[type=checkbox]{appearance:auto}.laws-app form{margin:18px 0}.law-text{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.75;margin:15px 0}.law-meta{font-size:12px;opacity:.8}.law-draft{border-left:3px solid #b88624;padding:14px;margin:18px 0}.law-error{color:#b83232;border:1px solid;padding:12px}.law-notice{border:1px solid #087f80;padding:12px}.laws-app pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}.laws-app summary{cursor:pointer}.laws-app a{color:var(--brand,#087f80)}.law-article{scroll-margin-top:90px}.laws-app :focus-visible{outline:2px solid var(--brand,#087f80);outline-offset:3px}@media(max-width:720px){.law-layout{grid-template-columns:1fr}.law-context{width:100%}}@media(prefers-color-scheme:dark){.laws-app{--law-bg:var(--surface,#1b2228);--law-text:var(--text,#ecf0f2);--law-line:var(--line,#3b454e)}}

.laws-app{border:1px solid var(--law-line);box-shadow:0 12px 40px #00000006;max-width:1360px}.law-heading{padding-bottom:24px;border-bottom:1px solid var(--law-line)}.law-heading p{max-width:640px;line-height:1.6;opacity:.7}.law-layout{grid-template-columns:280px minmax(0,1fr);gap:40px}.law-toc{position:sticky;top:90px;max-height:calc(100vh - 115px);overflow:auto;background:color-mix(in srgb,var(--law-text) 3%,var(--law-bg))}.law-toc h2{font-size:14px;text-transform:uppercase;letter-spacing:.06em;margin:26px 0 18px}.law-toc .toc-chapter h3{font-size:12px;opacity:.6;margin:22px 0 6px}.law-toc .toc-chapter button{border:0;font-size:13px;line-height:1.5;padding:8px;margin:2px 0}.toc-chapter button span{font-weight:700;margin-right:5px}.law-content{min-width:0}.law-content>h2{font-size:30px;letter-spacing:-.025em}.law-content>p{opacity:.7;line-height:1.7}.law-article{padding:28px 30px;border-radius:10px;margin:24px 0;box-shadow:0 3px 16px #00000003}.law-article>h3{font-size:22px;letter-spacing:-.015em}.law-article>footer{margin-top:24px;padding-top:16px;border-top:1px solid var(--law-line);font-size:12px;justify-content:flex-start}.law-meta{line-height:1.7}.law-subsection-editor{border:1px solid var(--law-line);border-radius:8px;margin:22px 0;padding:16px;min-width:0}.law-subsection-editor legend{font-weight:600;padding:0 8px}.law-subsection-editor>p{font-size:13px;opacity:.7}.law-part-editor{border-bottom:1px solid var(--law-line);padding-bottom:18px;margin-bottom:18px}.law-tools>label{min-width:160px}.law-book-select{font-size:12px}.law-book-select select{margin-top:8px;font-weight:600}@media(max-width:850px){.law-layout{grid-template-columns:1fr;gap:16px}.law-toc{position:static;max-height:320px}.law-article{padding:20px}.law-content>h2{font-size:25px}}
.editor-active{grid-template-columns:minmax(0,1fr);max-width:900px;margin-left:auto;margin-right:auto}.editor-active>.law-toc{display:none}.law-editor{padding:clamp(18px,3vw,32px);background:color-mix(in srgb,var(--law-text) 2%,var(--law-bg))}.law-editor .law-tools{justify-content:flex-start}.law-editor button[type=submit],.law-editor .law-tools>button:first-child{font-weight:600}
.law-search{padding:12px 18px}.law-search form{margin:0}.law-toc .toc-chapter .toc-subsection{padding-left:24px;font-size:12px;opacity:.7}
.editor-sections{display:flex;gap:8px;border-bottom:1px solid var(--law-line);padding-bottom:16px;margin-bottom:24px}.editor-sections [aria-pressed=true]{background:color-mix(in srgb,var(--brand,#087f80) 10%,transparent);border-color:var(--brand,#087f80)}
</style>
