<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue';
type Row = Record<string, any>;
const props = withDefaults(defineProps<{ endpoint?: string; cadUrl?: string }>(), { endpoint: '/api/social/laws.php', cadUrl: '' });
const state = ref<Row>({}), books = ref<Row[]>([]), selected = ref<Row | null>(null), articles = ref<Row[]>([]), rights = ref<Row>({}), admin = ref<Row>({authorities:[],grants:[],audit:[]});
const query = ref(''), error = ref(''), notice = ref(''), busy = ref(false), history = ref<Row[] | null>(null), editing = ref<Row | null>(null), newBook = ref(''), bookDescription = ref(''), publishDate = ref('');
const grant = ref<Row>({authority_id:0,draft_read:false,edit:false,publish:false,repeal:false});
const shown = computed(() => articles.value.filter(a => [a.number, a.current?.title,a.current?.chapter,a.current?.body,a.draft?.title,a.draft?.body,a.scheduled?.title].join(' ').toLocaleLowerCase().includes(query.value.toLocaleLowerCase())));
async function api(action:string, data?:Row, q:Row={}) {
 const response = await fetch(props.endpoint+'?'+new URLSearchParams({action,...q}),{credentials:'include',method:data?'POST':'GET',headers:data?{'Content-Type':'application/json','X-Laws-Request':'1'}:{},body:data?JSON.stringify(data):undefined});
 const result = await response.json();if(!response.ok)throw new Error(result.error||'Anfrage fehlgeschlagen.');return result;
}
async function run(fn:()=>Promise<void>) { if(busy.value)return;busy.value=true;error.value='';notice.value='';try{await fn();}catch(e){error.value=e instanceof Error?e.message:'Anfrage fehlgeschlagen.';}finally{busy.value=false;} }
async function refresh() { state.value=await api('bootstrap');if(state.value.enabled&&state.value.can_read||state.value.admin)books.value=(await api('books')).items;if(state.value.admin)admin.value=await api('administration'); }
async function open(id:number) {const r=await api('book',undefined,{id});selected.value=r.book;articles.value=r.articles;rights.value=r.rights;editing.value=null;history.value=null;query.value='';}
function edit(a?:Row) {const v=a?.draft||a?.current||a?.scheduled;editing.value={article_id:a?.id||0,book_id:selected.value!.id,revision:a?.revision||0,number:a?.number||'',title:v?.title||'',chapter:v?.chapter||'',body:v?.body||'',reason:a?.draft?.reason||''};}
async function saveDraft(){await api('save_draft',editing.value!);await open(Number(selected.value!.id));notice.value='Entwurf gespeichert. Die veröffentlichte Fassung bleibt unverändert.';}
async function publish(a:Row){let effective_at='';if(publishDate.value)effective_at=new Date(publishDate.value).toISOString().replace(/\.\d{3}Z$/,'Z');await api('publish',{article_id:a.id,revision:a.revision,effective_at});await open(Number(selected.value!.id));notice.value='Fassung veröffentlicht.';}
async function repeal(a:Row) {editing.value={repeal:true,article_id:a.id,revision:a.revision,number:a.number,reason:''};}
async function saveBook(){const r=await api('save_book',{title:newBook.value,description:bookDescription.value});newBook.value='';bookDescription.value='';await refresh();await open(r.id);}
async function saveGrant(){await api('grant',{...grant.value,book_id:selected.value!.id});await refresh();notice.value='Zuständigkeit gespeichert. Mitarbeiter benötigen zusätzlich passende CAD-Rollenrechte.';}
function loadGrant(){const existing=admin.value.grants.find((g:Row)=>Number(g.book_id)===Number(selected.value?.id)&&Number(g.authority_id)===Number(grant.value.authority_id));for(const key of ['draft_read','edit','publish','repeal'])grant.value[key]=!!Number(existing?.[key]||0);}
function articleLink(id:number){return location.href.split('#')[0]+(location.hash.startsWith('#/laws')?'#/laws/':'#law-')+id;}
async function followLink(){const linked=Number(location.hash.match(/(?:#\/laws\/|#law-)(\d+)/)?.[1]||0);if(linked&&state.value.can_read){for(const b of books.value){await open(Number(b.id));if(articles.value.some(a=>a.id===linked)){requestAnimationFrame(()=>document.getElementById('law-'+linked)?.scrollIntoView());break;}}}}
const onHash=()=>run(followLink);
onMounted(()=>{window.addEventListener('hashchange',onHash);run(async()=>{await refresh();await followLink();});});
onUnmounted(()=>window.removeEventListener('hashchange',onHash));
</script>
<template>
<section class="laws-app" :aria-busy="busy">
 <header class="law-heading"><div><span class="law-eyebrow">ÖFFENTLICHES GESETZBUCH</span><h1>Gesetze</h1><p>Geltende Fassungen, Änderungen und Zuständigkeiten deiner Community.</p></div><span class="law-context">{{ state.context ? 'CAD · '+state.context.name : 'Leseansicht' }}</span></header>
 <p v-if="error" class="law-error" role="alert">{{error}}</p><p v-if="notice" class="law-notice" role="status">{{notice}}</p>
 <p v-if="state.enabled===false">Die Gesetze-App ist deaktiviert.</p>
 <p v-else-if="state.can_read===false">Zum Lesen bitte anmelden. Der Gastzugang für Gesetze ist derzeit ausgeschaltet.</p>
 <a v-if="cadUrl&&!state.context" :href="cadUrl.replace(/\/$/,'')+'/laws'" target="_blank" rel="noopener">Im CAD öffnen und bearbeiten ↗</a>
 <details v-if="state.admin" class="law-panel"><summary>Community-Verwaltung</summary>
  <form @submit.prevent="run(async()=>{await api('settings',{enabled:state.enabled,guest:state.guest,revision:state.revision});await refresh();notice='Einstellungen gespeichert.';})"><label class="law-check"><input type="checkbox" v-model="state.enabled"/>Gesetze-App aktiviert</label><label class="law-check"><input type="checkbox" v-model="state.guest"/>Veröffentlichte Gesetze ohne Anmeldung lesbar</label><button :disabled="busy">Einstellungen speichern</button></form>
  <form @submit.prevent="run(saveBook)"><h3>Gesetzbuch anlegen</h3><label>Titel<input v-model="newBook" required maxlength="160" placeholder="Zum Beispiel Strafgesetzbuch"/></label><label>Beschreibung<textarea v-model="bookDescription" maxlength="4000"/></label><button :disabled="busy">Gesetzbuch anlegen</button></form>
  <details><summary>Änderungsprotokoll</summary><ol><li v-for="entry in admin.audit" :key="entry.id">{{entry.created_at}} UTC · {{entry.action}} · CAD-Benutzer {{entry.actor_id}} / Fraktion {{entry.authority_id}}<pre>{{entry.details}}</pre></li></ol></details>
 </details>
 <div v-if="state.can_read&&(state.enabled||state.admin)" class="law-layout">
  <nav class="law-panel" aria-label="Gesetzbücher"><h2>Gesetzbücher</h2><p v-if="!books.length">Noch keine Gesetzbücher angelegt.</p><button v-for="b in books" :key="b.id" :class="{active:selected?.id===b.id}" :aria-pressed="selected?.id===b.id" :disabled="busy" @click="run(()=>open(Number(b.id)))">{{b.title}}</button></nav>
  <main v-if="selected" class="law-content"><h2>{{selected.title}}</h2><p>{{selected.description}}</p>
   <details v-if="state.admin" class="law-panel"><summary>Gesetzbuch und Fraktionszuständigkeiten</summary>
    <form @submit.prevent="run(async()=>{await api('save_book',selected!);await refresh();await open(Number(selected!.id));})"><label>Titel<input v-model="selected.title" maxlength="160" required/></label><label>Beschreibung<textarea v-model="selected.description" maxlength="4000"/></label><button :disabled="busy">Gesetzbuch speichern</button></form>
    <form @submit.prevent="run(saveGrant)"><label>Fraktion<select v-model="grant.authority_id" @change="loadGrant" required><option :value="0" disabled>Fraktion auswählen</option><option v-for="a in admin.authorities" :key="a.id" :value="Number(a.id)">{{a.display_name}}</option></select></label><label v-for="[key,label] in [['draft_read','Entwürfe lesen'],['edit','Bearbeiten'],['publish','Veröffentlichen'],['repeal','Außer Kraft setzen']]" :key="key" class="law-check"><input type="checkbox" v-model="grant[key]"/>{{label}}</label><p>Die Freigabe gilt nur für dieses Gesetzbuch. Alle Haken entfernen entzieht die Zuständigkeit.</p><button :disabled="busy||!grant.authority_id">Zuständigkeit speichern</button></form>
   </details>
   <div class="law-tools"><label>Paragraphen durchsuchen<input v-model="query" type="search" placeholder="Nummer, Titel oder Inhalt"/></label><button v-if="rights.edit" :disabled="busy" @click="edit()">Paragraph anlegen</button></div>
   <form v-if="editing" class="law-panel law-editor" @submit.prevent="run(async()=>{if(editing!.repeal){await api('repeal',editing!);await open(Number(selected!.id));notice='Fassung außer Kraft gesetzt.';}else await saveDraft();})">
    <h3>{{editing.repeal?'Außer Kraft setzen: § '+editing.number:'Entwurf bearbeiten'}}</h3>
    <template v-if="!editing.repeal"><label>Paragraphennummer<input v-model="editing.number" :disabled="!!editing.article_id" required maxlength="40"/></label><label>Kapitel<input v-model="editing.chapter" maxlength="160"/></label><label>Titel<input v-model="editing.title" required maxlength="200"/></label><label>Gesetzestext<textarea v-model="editing.body" rows="12" required maxlength="100000"/></label></template>
    <label>Begründung<textarea v-model="editing.reason" required maxlength="4000"/></label><div class="law-tools"><button :disabled="busy">{{editing.repeal?'Aufhebung bestätigen':'Entwurf speichern'}}</button><button type="button" :disabled="busy" @click="editing=null">Abbrechen</button></div>
   </form>
   <label v-if="rights.publish" class="law-panel">Neue Veröffentlichungen gültig ab (leer = sofort)<input type="datetime-local" v-model="publishDate"/><small>Die ausgewählte Zeit entspricht deiner lokalen Zeitzone.</small></label>
   <p v-if="!shown.length">Keine sichtbaren Paragraphen gefunden.</p>
   <article v-for="a in shown" :key="a.id" :id="'law-'+a.id" class="law-panel law-article">
    <h3>§ {{a.number}} · {{(a.current||a.scheduled||a.draft)?.title}}</h3>
    <template v-if="a.current"><span class="law-badge">{{a.current.repealed_at?'Außer Kraft':'Geltende Fassung'}}</span><p class="law-meta">{{a.current.chapter}} · Gültig seit {{a.current.effective_at}} UTC · Herausgeber: {{a.current.publisher}}</p><div class="law-text">{{a.current.body}}</div><p v-if="a.current.repealed_at">Außer Kraft seit {{a.current.repealed_at}} UTC: {{a.current.repeal_reason}}</p></template>
    <p v-else>Dieser Paragraph hat noch keine geltende Fassung.</p>
    <details v-if="a.scheduled"><summary>Zukünftige Fassung · gültig ab {{a.scheduled.effective_at}} UTC</summary><h4>{{a.scheduled.title}}</h4><div class="law-text">{{a.scheduled.body}}</div></details>
    <details v-if="a.draft" class="law-draft" open><summary>Entwurf · nicht veröffentlicht</summary><h4>{{a.draft.title}}</h4><div class="law-text">{{a.draft.body}}</div><p>Begründung: {{a.draft.reason}}</p><button v-if="rights.publish" :disabled="busy" @click="run(()=>publish(a))">Diese Fassung veröffentlichen</button><button v-if="rights.edit" :disabled="busy" @click="run(async()=>{await api('discard',{article_id:a.id,revision:a.revision});await open(Number(selected!.id));})">Entwurf verwerfen</button></details>
    <footer class="law-tools"><a :href="articleLink(a.id)">Direktlink</a><button :disabled="busy" @click="run(async()=>{history=(await api('history',undefined,{id:a.id})).items;})">Frühere Fassungen</button><button v-if="rights.edit" :disabled="busy" @click="edit(a)">{{a.draft?'Entwurf bearbeiten':'Änderung entwerfen'}}</button><button v-if="rights.repeal&&a.current&&!a.current.repealed_at" :disabled="busy" @click="repeal(a)">Außer Kraft setzen</button></footer>
   </article>
   <section v-if="history" class="law-panel"><h3>Veröffentlichte Fassungen</h3><button @click="history=null">Schließen</button><p v-if="!history.length">Noch keine veröffentlichten Fassungen.</p><article v-for="v in history" :key="v.id"><h4>{{v.title}} · {{v.effective_at}} UTC</h4><p>{{v.publisher}} · {{v.reason}}</p><div class="law-text">{{v.body}}</div><hr/></article></section>
  </main><main v-else><p>Wähle ein Gesetzbuch aus.</p></main>
 </div>
</section>
</template>
<style scoped>
.laws-app{--law-bg:var(--surface,#fff);--law-text:var(--text,#202c35);--law-line:var(--line,#d7dee2);color:var(--law-text);background:var(--law-bg);padding:clamp(16px,3vw,36px);border-radius:18px;max-width:1280px;margin:20px auto;font:inherit;min-height:60vh}.law-heading,.law-tools{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap}.law-heading{margin-bottom:24px}.law-eyebrow{font-size:11px;letter-spacing:.16em}.laws-app h1{font-size:32px;margin:8px 0}.laws-app h2{font-size:23px}.laws-app h3{font-size:18px;line-height:1.4;margin:0 0 12px}.laws-app p{margin:12px 0}.law-context,.law-badge{display:inline-block;padding:6px 10px;border:1px solid var(--law-line);border-radius:8px;font-size:12px}.law-layout{display:grid;grid-template-columns:230px minmax(0,1fr);gap:24px;margin-top:22px}.law-panel{border:1px solid var(--law-line);border-radius:12px;padding:18px;margin-bottom:16px}.law-layout nav{align-self:start}.law-layout nav button{display:block;width:100%;text-align:left;margin:8px 0}.laws-app button{font:inherit;color:inherit;border:1px solid var(--law-line);border-radius:8px;background:transparent;padding:9px 12px;cursor:pointer}.laws-app button:disabled{opacity:.5;cursor:wait}.laws-app button.active,.laws-app button:hover:not(:disabled){border-color:var(--brand,#087f80);background:color-mix(in srgb,var(--brand,#087f80) 10%,transparent)}.laws-app input:not([type=checkbox]),.laws-app textarea,.laws-app select{display:block;width:100%;font:inherit;color:inherit;background:var(--law-bg);border:1px solid var(--law-line);padding:9px;border-radius:6px;box-sizing:border-box}.laws-app label{display:block;margin:12px 0;flex:1}.laws-app .law-check{display:flex;align-items:center;gap:8px}.laws-app input[type=checkbox]{appearance:auto}.laws-app form{margin:18px 0}.law-text{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.75;margin:15px 0}.law-meta{font-size:12px;opacity:.8}.law-draft{border-left:3px solid #b88624;padding:14px;margin:18px 0}.law-error{color:#b83232;border:1px solid;padding:12px}.law-notice{border:1px solid #087f80;padding:12px}.laws-app pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}.laws-app summary{cursor:pointer}.laws-app a{color:var(--brand,#087f80)}.law-article{scroll-margin-top:90px}.laws-app :focus-visible{outline:2px solid var(--brand,#087f80);outline-offset:3px}@media(max-width:720px){.law-layout{grid-template-columns:1fr}.law-context{width:100%}}@media(prefers-color-scheme:dark){.laws-app{--law-bg:var(--surface,#1b2228);--law-text:var(--text,#ecf0f2);--law-line:var(--line,#3b454e)}}
</style>
