import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import {resolve} from 'node:path';
test('laws: CAD publisher interface, safe text, public history and mobile reading',async({page,context,baseURL})=>{
 const token=execFileSync('docker-compose',['-f','backend/social/tests/compose.yml','exec','-T','backend','cat','/tmp/laws-test-session'],{cwd:resolve(process.cwd(),'..'),encoding:'utf8'}).trim();
 await context.addCookies([{name:'auth_token',value:token,url:baseURL!}]);
 await page.goto('/#/laws');
 await expect(page.getByRole('heading',{name:'Gesetze',exact:true})).toBeVisible();
 await page.getByText('Neues Gesetzbuch',{exact:true}).click();
 await page.getByRole('button',{name:'Straßenverkehrsordnung',exact:true}).click();
 await expect(page.locator('form').filter({has:page.getByRole('heading',{name:'Gesetzbuch anlegen'})}).getByLabel('Titel',{exact:true})).toHaveValue('Straßenverkehrsordnung');
 await page.locator('form').filter({has:page.getByRole('heading',{name:'Gesetzbuch anlegen'})}).getByLabel('Titel',{exact:true}).fill('Straßenverkehr');
 await page.locator('form').filter({has:page.getByRole('heading',{name:'Gesetzbuch anlegen'})}).getByLabel('Beschreibung',{exact:true}).fill('Regeln für die Straßen');
 await page.getByRole('button',{name:'Gesetzbuch anlegen',exact:true}).click();
 await page.getByRole('button',{name:'Paragraph anlegen'}).click();
 await page.getByLabel('Paragraphennummer',{exact:true}).fill('12');
 await page.locator('.law-editor').getByLabel('Titel',{exact:true}).fill('Vorfahrt');
 await page.getByLabel('Gesetzestext').fill('Sicher fahren. <script>alert(1)</script>');
 await page.getByRole('button',{name:'Absatz hinzufügen'}).click();
 await page.getByLabel('Absatznummer',{exact:true}).fill('1');
 await page.getByLabel('Zwischenüberschrift',{exact:true}).fill('An Kreuzungen');
 await page.getByLabel('Absatztext',{exact:true}).fill('Auf querenden Verkehr achten.');
 await page.getByLabel('Betrag / Mindestbetrag (RP-$)',{exact:true}).fill('250');
 await page.getByLabel('Höchstbetrag (optional, RP-$)',{exact:true}).fill('750');
 await page.locator('.law-editor').getByLabel('Begründung').fill('Neue Vorschrift');
 await page.getByRole('button',{name:'Vorschau',exact:true}).click();
 await expect(page.locator('.law-editor .law-amount')).toContainText('250 – 750 RP-$');
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:'test-results/laws-editor.png',fullPage:true});
 await page.getByRole('button',{name:'Weiter bearbeiten',exact:true}).click();
 await page.getByRole('button',{name:'Entwurf speichern',exact:true}).click();
 await expect(page.getByText('Entwurf · nicht veröffentlicht')).toBeVisible();
 await page.getByRole('button',{name:'Diese Fassung veröffentlichen'}).click();
 await expect(page.getByText('Geltende Fassung',{exact:true})).toBeVisible();
 await expect(page.getByRole('navigation',{name:'Inhaltsverzeichnis'})).toContainText('Vorfahrt');
 await expect(page.locator('.law-amount')).toContainText('250 – 750 RP-$');
 const link=await page.getByRole('link',{name:'Direktlink'}).getAttribute('href');
 await context.clearCookies();
 await page.goto(link!);
 await page.reload();
 await expect(page.getByRole('heading',{name:'§ 12 · Vorfahrt'})).toBeVisible();
 await expect(page.getByRole('button',{name:'Änderung entwerfen'})).toHaveCount(0);
 await expect(page.locator('.law-text').first()).toContainText('<script>alert(1)</script>');
 await page.getByLabel('Alle Gesetzbücher durchsuchen').fill('Vorfahrt');
 await page.getByRole('button',{name:'Suchen',exact:true}).click();
 await expect(page.getByRole('heading',{name:'1 Treffer'})).toBeVisible();
 await page.locator('.law-result').click();
 await expect(page.getByRole('heading',{name:'§ 12 · Vorfahrt'})).toBeVisible();
 await expect(page.locator('.law-subsection')).toContainText('Auf querenden Verkehr achten.');
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:'test-results/laws-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:'test-results/laws-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'Dunkler Modus'}).click();
 await page.screenshot({path:'test-results/laws-dark.png',fullPage:true});
});
